### ISSUE TITLE
在打开相机后，直接退出会报Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by zjianflys** [huweigoodboy/SweetCamera#4]
public void releaseActivityCamera() {
        if (mActivityCamera != null) {
            try {
                mActivityCamera.release();
                mActivityCamera.stopPreview();
                mActivityCamera.setPreviewCallback(null);
                mActivityCamera.setPreviewCallbackWithBuffer(null);
                mActivityCamera = null;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

要把release()提前,就解决了

**Comment by huweigoodboy** [comment]
感谢你的反馈，代码已经同步更新。
